name: tlx
options:
  bundleIdPrefix: com.achempion
  deploymentTarget:
    iOS: "17.0"
packages:
  swift-nio-ssh:
    url: https://github.com/apple/swift-nio-ssh
    exactVersion: 0.15.0
targets:
  tlx:
    type: application
    platform: iOS
    sources: [Sources]
    settings:
      INFOPLIST_FILE: Info.plist
    dependencies:
      - framework: Core.xcframework
        embed: false
      - package: swift-nio-ssh
        product: NIOSSH
  tlxTests:
    type: bundle.unit-test
    platform: iOS
    sources: [Tests]
    settings:
      GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: tlx
schemes:
  tlx:
    build:
      targets:
        tlx: all
    test:
      targets: [tlxTests]
